### ISSUE TITLE
Relax obs version requirement?

### ISSUE THREAD

**Issue by satu** [dnaka91/obws#11]
Currently the library requires OBS 26.1.2, however that is a macOS hotfix and the OBS repositories for Ubuntu LTS haven't bumped the version, staying at 26.1.1. Can the version requirement be relaxed?

**Comment by dnaka91** [comment]
Oh I didn't know that was a MacOS specific fix. I'll change it to be `26.1.0` tomorrow as fix releases usually don't make any breaking changes.

Would that work out for you?

**Comment by satu** [comment]
that would work. thanks!

**Comment by dnaka91** [comment]
I just released a version with this detail fixed. Unfortunately it's not a fix release as I pushed some other changes with together with it.
