### ISSUE TITLE
How to get/set source settings for Xcomposite source

### ISSUE THREAD

**Issue by Kirottu** [dnaka91/obws#16]
I am trying to alter settings for my Xcomposite window capture source and first trying to get them, but I keep acing the issue of `type inside \`async\` block must be known in this context` with the `get_source_settings()` function.

**Comment by dnaka91** [comment]
The `source_settings` field of the `SourceSettings` response is generic and can be any value that can be deserialized by the `serde` crate. That means you have to pass in the type that should be deserialized.

For example:

```rust
// Define some custom settings struct that is valid for the source.
#[derive(serde::Deserialize)]
struct XCompositeCapture {
    value_1: String,
    value_2: u64,
}

// Load the settings, passing the type to `get_source_settings`
let settings = client.sources().get_source_settings::<XCompositeCapture>().await?;

// Or define the type on the variable directly
let settings: XCompositeCapture = client.sources().get_source_settings().await?;
```

If you're not sure yet how the data of the source may look like, you can use for example `serde_json::Value` and inspect the data.

```rust
let settings = client.sources().get_source_settings::<serde_json::Value>().await?;
// Print the `serde_json::Value` back out as JSON string
println!("{:?}", serde_json::to_string_pretty(&settings.source_settings)?);
```

**Comment by Kirottu** [comment]
Ah I see, got it working properly now. Thanks!
