### ISSUE TITLE
Error decoding into `response::TextGdiPlusProperties`

### ISSUE THREAD

**Issue by peddermaster2** [dnaka91/obws#17]
In my OBS (v27.2.1) with obs-websocket (v4.9.1) the response to a `GetTextGDIPlusProperties` request can not be deserialized by this library. "the response message could not be deserialized"

The response that is send from obs-websocket is here (formatted for readability):

```json
{
    "align": "center",
    "antialiasing": true,
    "bk_color": 4286513152,
    "bk_opacity": 0,
    "chatlog": false,
    "chatlog_lines": 6,
    "color": 16777215,
    "extents": false,
    "extents_cx": 100,
    "extents_cy": 100,
    "extents_wrap": true,
    "font": {
        "face": "Beon",
        "flags": 0,
        "size": 256,
        "style": "Medium"
    },
    "gradient_color": 16777215,
    "gradient_dir": 90.0,
    "gradient_opacity": 100,
    "message-id": "4",
    "opacity": 100,
    "outline": true,
    "outline_color": 4278190165,
    "outline_opacity": 100,
    "outline_size": 10,
    "source": "Multiplayer Code",
    "status": "ok",
    "text": "Lobby: 1yd5r",
    "transform": 0,
    "valign": "bottom"
}
```

**Comment by peddermaster2** [comment]
@dnaka91 could you take a look at this?

**Comment by dnaka91** [comment]
Hey @peddermaster2 thanks for opening the issue and making a PR for it as well.

The problem why this happened is that I couldn't really test the GDI+ version as I'm not working on Windows and don't have any Windows device around.

The PR looks good to me, and I think I'll just merge this and make a fix release.

**Just 1 thing I would like you to try:** Can you make a new GDI+ scene item and leave everything in the property dialog as is, adding it without any change, then get the settings through `obws`?

OBS omits most of the fields that are set to the default, so my concern is, that there may be potentially more fields that need a `#[serde(default)]` annotation.

**Comment by peddermaster2** [comment]
While I was at it, I also tested this for the TextFreetype2Properties. It is the same response. But the current implementation has no `#[serde(default)]` for the `text` field. Should I fix that as well?

**Comment by dnaka91** [comment]
Thanks a bunch, I saw you already updated the Freetype2 source as well 🎉.
Will just let the CI run once now, merge it and cut a new patch release.
