### ISSUE TITLE
Unable to connect - deserialize error

### ISSUE THREAD

**Issue by Elinvynia** [dnaka91/obws#21]
OS: Fedora 36
OBS version: 27.2.4 flatpak
obs-websocket version: 5.0.0-beta1
obws version:  https://github.com/dnaka91/obws/commit/efd6170067232628481468ce5b872baacce47724 (aka latest for v5 api)

Full error: 
```
Error: the response message could not be deserialized

Caused by:
    missing field `platform`
```

Happens immediatelly when calling collect, so I can't test further API endpoints.

obs-websocket sends two notifications: "client identified" and "client disconnected"

Can provide further help with debugging as this is 100% reproducible

**Comment by dnaka91** [comment]
Hi @Elinvynia, field that is only in the very latest `5.0.0`, and not available in the `beta1` version. I'm currently targeting/updating for the very latest changes, until the full v5 is released. Therefore, it fails with the beta version.

You can grab a more recent build of `obs-websocket` here: https://github.com/obsproject/obs-websocket/actions/runs/2322691969.

**Comment by dnaka91** [comment]
Ah, that's unfortunate. They put build info in the prerelease part, causing the version check to fail (should better be build meta like `5.0.0+91cabe1`, in my opinion). Didn't notice that, as I currently compile OBS + obs-websocket myself.

I added a temporary fix that strips the prerelease info before the version check (that I'll remove again, once the full v5 is out).

If anything else comes up, just let me know. I'm very happy to have somebody test the v5 API, besides me 😄.

**Comment by Elinvynia** [comment]
The latest commit seems to fail CI and also doesn't build locally :(

**Comment by Elinvynia** [comment]
Thanks a lot!

I can confirm it works, even the few APIs I need for my specific functions (mute and scene switch)
