### ISSUE TITLE
Connection timeout duration

### ISSUE THREAD

**Issue by ori-sky** [dnaka91/obws#36]
I'm using obws as part of a web server that allows configuration of the remote OBS connection details, and I'd like to be able to set a timeout duration in case the remote OBS is not currently running. As it stands, awaiting on the connection appears to wait indefinitely with no timeout -- is there a way to do this or is this something that would be feasible to add as a new feature?

**Comment by dnaka91** [comment]
Yes, connection handling is currently very bare bones and as of now you can't configure a timeout through obws's API.

I think this is a good addition so I'll extend the [`connect_with_config`](https://docs.rs/obws/latest/obws/client/struct.Client.html#method.connect_with_config). Also, I'll look into adding some new connection option which takes any `AsyncRead + AsyncWrite` as parameter so you can customize and wrap the TCP connection before handing it over to obws.

The `tokio-tungstenite` crate already has such functions, making it potentially straight forward to add those in.

**Comment by dnaka91** [comment]
I released a new version which now has a `connect_timeout` field on the `ConnectConfig` struct that you can use to customize the timeout.

Furthermore, the regular `Client::connect` method now uses a timeout of _30 seconds_ which should be a decent default for most cases.
