### ISSUE TITLE
Implement obs-websocket 5.4 features

### ISSUE THREAD

**Issue by peddermaster2** [dnaka91/obws#38]
The new version of OBS (30.1) contains version 5.4.2 of the obs-websocket library. It would be great if the [new features and changes](https://github.com/obsproject/obs-websocket/releases/tag/5.4.0) could be implemented (and released) in this repo.

**Comment by dnaka91** [comment]
Thank you for the reminder ☺️.

This is currently in progress already, and involved a rather large API change for the addition of the new UUID fields.

Just not 100% happy with the ergonomics around this yet, but will release it relatively soon.

**Comment by dnaka91** [comment]
I just released v0.12 which features all the new additions from obs-websocket v5.4 but includes several breaking changes as well.

As mentioned, those improve the Rust API around the UUID identifiers and avoids the problem of accidentally setting both name and UUID of an element in any request (which is invalid for the obs-websocket).

Maybe there are still a few rough edges around those adjustments but those can likely be improved in future releases without having an API break again.
