### ISSUE TITLE
Can I get the video stream?

### ISSUE THREAD

**Issue by BrokenWingsIcarus** [dnaka91/obws#41]
I noticed that only images can be retrieved in the current document.

**Comment by dnaka91** [comment]
You cannot, as the obs-websocket API doesn't provide it. This is not really something I can implement, and better to ask at the obs-websocket project, if you need it.

The only thing that you could do is to trigger the replay buffer to save to a file, but there is nothing to get a constant stream of the current video output.

**Comment by BrokenWingsIcarus** [comment]
thank you.
