### ISSUE TITLE
No need to verify obs studio version?

### ISSUE THREAD

**Issue by LuiScreaMed** [dnaka91/obws#42]
Since im using obs studio 28.0, i encountered connection error caused by obs version verification.
Actually it seems no need to verify obs studio version, I've tried commenting out the related codes (src/client/mod.rs line 333), and it runs well. 
I believe it's okay to remove the obs version verification and retain the verification for the websocket version and rpc version, as they really matter.

**Comment by dnaka91** [comment]
This is not really a requirement for obws, but rather for the obs-websocket plugin. It is tightly tied to the version of OBS and nowadays even shipped together with it.

They require a certain version of OBS to work, so if you have the latest version of obs-websocket combined with an older OBS it may work but is likely to fail at some point.

So for obws it's rather a safety feature to avoid potentially problematic setups, which have caused many issue reports on the obs-websocket issue tracker in the past so I wanted to avoid similar things here.
