### ISSUE TITLE
Send_message blocks forever waiting for response

### ISSUE THREAD

**Issue by 715209** [dnaka91/obws#7]
While sending a message to the WebSocket if OBS or the WebSocket suddenly crashes it will wait forever for a response.

![image](https://user-images.githubusercontent.com/5977687/110804705-b4762b00-8280-11eb-899b-47a61de8e97b.png)

https://github.com/dnaka91/obws/blob/b25ea51a15d826a1a50f004e09c071c57c9fd9be/src/client/mod.rs#L293-L295

**Comment by dnaka91** [comment]
Thank you for reporting this. Sorry, you find so many rough edges in regards to crashing OBS. For me it almost never crashes so I simply don't get into this situations.

I see we problem here. We put the oneshot Sender in a map but never clear the map when we get out of the event loop. Therefore, the sender isn't dropped and we wait forever.

I'll prepare a fix tomorrow. 

After that I'll look into building a dummy websocket server to emulate obs-websocket. That should allow to write unit tests for the core handling logic of the client against these cases.

**Comment by dnaka91** [comment]
As you probably already saw, I pushed a change yesterday that should fix this.

I'll make a new release today.

**Comment by 715209** [comment]
Yes, thank you for that :smile:
